### ISSUE TITLE
Update the default solidity version

### ISSUE THREAD

**Issue by its-everdred** [ConsenSys-archive/truffle#4364]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

A fresh truffle init will default to using Solidity v0.5.16, which is almost 2 years old.

## Steps to Reproduce

```
truffle init
truffle compile
```

## Expected Behavior

Truffle should compile with a version of `solc` that is current.

## Actual Results

```
> Compiled successfully using:
   - solc: 0.5.16
```

## Potential Solution

Changing the default would break Truffle projects in the wild and force developers to migrate their projects, which is unacceptable.  Instead, running `truffle init` could provide a current version within `truffle-config.js` so that new projects aren't relying on truffle's outdated default.

## Environment

* Operating System: macOS Big Sur, 11.6
* Ethereum client:
* Truffle version (`truffle version`): v5.4.11 (core: 5.4.11)
* node version (`node --version`): v16.0.0
* npm version (`npm --version`): 7.10.0

**Comment by gnidan** [comment]
One approach I've had in mind for this is that we can create a user-level config (`~/.config/truffle/...`) parameter called "default Solidity version" and use that moving forward. This parameter would control the default at the project-level (`truffle-config.js`), so users could configure Truffle "globally" to set their preferred default for all projects moving forward. This would not be breaking, because the default user-level default would remain 0.5.16, but we could encourage people to upgrade this way.

**Comment by fainashalts** [comment]
@kevinweaver's idea is the one most likely to be successful here -- update the default in the config on `truffle init`; we will also want to update the default box compiler versions as well (carefully! as some of these may need older Solidity versions).

**Comment by haltman-at** [comment]
Closing this for now now that #4371 is merged, but we'll likely want to revisit this in some form later.
